# Dockerfile for producer
FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY kafka_producer.py kafka_producer.py

CMD ["python", "kafka_producer.py"]
